[package]
name = "tcpnet"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "A simple TCP-based message transport for games that runs on Tokio"
categories = ["network-programming"]
readme = "README.md"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
